name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@4cd397a333e5500c1683589c277f56a3c10990e6
        with:
          # Use PAT if available, fallback to GITHUB_TOKEN
          # PAT may be needed for certain repository configurations
          token: ${{ secrets.GITHUB_TOKEN || secrets.MY_RELEASE_PLEASE_TOKEN }}
          # Use config file for more flexible configuration
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
